### PR TITLE
Migrate NUnit assertions to the constraint model in preparation of the NUnit 4 upgrade

### PR DESCRIPTION
**Pull request by danielmarbach**
This PR contains all changes related to assertion model according to the [constraint assertion model](https://docs.nunit.org/articles/nunit/writing-tests/assertions/assertion-models/constraint.html).

Using a script, we apply all [assertion rules](https://docs.nunit.org/articles/nunit-analyzers/NUnit-Analyzers.html#assertion-rules-nunit2001---) provided by the NUnit.Analyzers package. In addition, some manual interventions are done when applicable.

## Plan of action

- [x] ⚠️ Build the solution and resolve any remaining errors or warnings
- [x] ✅ Review the assertions commit by commit
- [x] 👀 Invite another pair of eyes to re-review
- [x] 🏗 Set the PR to _In progress_ on the board

### CODE REVIEW

**Review by lailabougria — CHANGES_REQUESTED** [review]
I believe the following packages are missing the analzyer:
- https://github.com/Particular/NServiceBus.Persistence.AzureTable/tree/master/src/TransactionalSession.StorageTable.AcceptanceTests
- https://github.com/Particular/NServiceBus.Persistence.AzureTable/tree/master/src/TransactionalSession.CosmosDB.AcceptanceTests

Even though they pull in other tests, if we add the analyzer and specific tests are added to each individual project in time, we will catch it.

**Comment by danielmarbach** [comment]
Funny enough, this is the PR where I did not auto-replace `Nunit` with `NUnit`. Good catch

**Comment by danielmarbach** [comment]
@lailabougria addressed the comment. See https://github.com/Particular/NServiceBus.Persistence.AzureTable/pull/972/commits/b342aa0f0fcc43e5a3b4fe7a4517795b657c3d90 and https://github.com/Particular/NServiceBus.Persistence.AzureTable/pull/972/commits/fe3f88406bcd5e82ffac9294f8671dfdeae5340b

**Comment by cquirosj** [comment]
Resolved merge conflicts https://github.com/Particular/NServiceBus.Persistence.AzureTable/pull/972/commits/fe7ffebaf050c1071cf067fdd5ac33badb90b9a9

**Review by lailabougria — APPROVED** [review]

**Pull request merged**
