### PR TITLE
Fix Outbox table creation bug

### PR DESCRIPTION
**Pull request by jpalac**
Fixes:
- https://github.com/Particular/NServiceBus.Persistence.AzureTable/issues/717

### CODE REVIEW

**Review by abparticular — APPROVED** [review]
LGTM

**Comment by jpalac** [comment]
@danielmarbach I saw that you reviewed [the previous PR](https://github.com/Particular/NServiceBus.Persistence.AzureTable/pull/730) on this. I've tried to incorporate your comments from it - could you please give this a quick review to see if there are any red flags?
(I was too trigger happy and pressed merged after Andreas reviewed - can always do another PR if need be)

**Comment by danielmarbach** [comment]
@jpalac done. I only had limited time. Hopefully, the input is valuable

**Comment by jpalac** [comment]
Thanks @danielmarbach - I've addressed these in https://github.com/Particular/NServiceBus.Persistence.AzureTable/pull/1031

**Pull request merged**
